### ISSUE TITLE
jpa persistence xsd mixed version

### ISSUE THREAD

**Issue by spassignat** [datanucleus/javax.persistence#13]
The artefact org.datanucleus:javax.persistence:2.2.0-release embedded the persistence_2_1.xsd. This xsd file force the version of the persistence.xml to version 2.0.

IntelliJ => force the use of this 2.0 version
Eclipse => force the use of this 2.1 version (because it validate the file with its own xsd file)

**Comment by spassignat** [comment]
I can fix it if needed

**Comment by andyjefferson** [comment]
javax.persistence is currently at v2.2.2. It *provides* persistence_1_0.xsd, persistence_2_0.xsd, persistence_2_1.xsd AND persistence_2_2.xsd. Just like the EclipseLink variant of the same thing.
